### ISSUE TITLE
[両方] 決済処理後デポジット額が変化しない

### ISSUE THREAD

**Issue by ProfFunami** [enpitut2019/MedicalPaymentService#21]
デポジット追加はできるが、決済処理したあと両者の画面上のデポジット額が変化しない。

etherscanを見たら決済後のデポジットも変わらなかったので、決済がされてないと思われる。
ちなみに決済時のコンソールを見てもエラーは出ていない。

**Comment by kt-chn** [comment]
昨日治した、fetch/margeもしくはpull
